# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
servers = [
    {
        :name => "ubuntu",
        :type => "master",
        :box => "generic/ubuntu2204",
        :enp0s8 => "192.168.33.10",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "worker1",
        :type => "node",
        :box => "generic/ubuntu2204",
        :enp0s8 => "192.168.33.10",
        :mem => "2048",
        :cpu => "2"
    }
]

# This script to install k8s using kubeadm will get executed after a box is provisioned
$configureBox = <<-SCRIPT
    #apt-get update
    #apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    # add nico user
    sudo adduser nico --gecos "Nico Kruger,RoomNumber,WorkPhone,HomePhone" --disabled-password
    echo "nico:nico@123" | sudo chpasswd
    # add nico pub key
    mkdir -p /home/nico/.ssh
    echo "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEED62Zh6X7y60Wjbs0ZUaC0ydIh2Q7VUI1SBzQhz1YcgB2NTxkYkhhfVdgG6bcBE4sft7PlGim2hvYtlRj95zY= linic@cyberx" >> /home/nico/.ssh/authorized_keys
    chmod -R go= /home/nico/.ssh
    chown -R nico:nico /home/nico/.ssh
    # install mdns
    #hostnamectl set-hostname ubuntu
    sudo apt install avahi-daemon -y
    systemctl start avahi-daemon
    systemctl enable avahi-daemon
SCRIPT


Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.hostname = opts[:name]
            #config.vm.network :private_network, ip: opts[:enp0s8]
            config.vm.network "public_network", use_dhcp_assigned_default_route: true

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            # we cannot use this because we can't install the docker version we want - https://github.com/hashicorp/vagrant/issues/4871
            #config.vm.provision "docker"

            config.vm.provision "shell", inline: $configureBox


        end

    end

end 